# Generated by Django 4.2.16 on 2026-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_school_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='career_interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
