# Generated by Django 4.2.16 on 2026-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_bio_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
