# Generated by Django 4.2.16 on 2026-08-01 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_legacy_memberships(apps, schema_editor):
    StudentProfile = apps.get_model('accounts', 'StudentProfile')
    StudentSchoolMembership = apps.get_model(
        'accounts',
        'StudentSchoolMembership',
    )

    memberships = []
    for profile in StudentProfile.objects.filter(
        school__isnull=False,
        school_membership_status__in=['active', 'pending', 'rejected'],
    ).iterator():
        status = profile.school_membership_status
        memberships.append(
            StudentSchoolMembership(
                student_profile_id=profile.pk,
                school_id=profile.school_id,
                status=status,
                record_source='legacy_backfill',
                active_identity_key=(
                    profile.pk if status == 'active' else None
                ),
                pending_identity_key=(
                    profile.pk if status == 'pending' else None
                ),
                requested_at=None,
                started_at=None,
            )
        )
    StudentSchoolMembership.objects.bulk_create(memberships)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_expand_student_profile_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('ended', 'Ended')], max_length=20)),
                ('record_source', models.CharField(choices=[('legacy_backfill', 'Legacy Backfill'), ('learner_request', 'Learner Request')], default='learner_request', max_length=20)),
                ('active_identity_key', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('pending_identity_key', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_student_school_memberships', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_memberships', to='accounts.school')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
            },
        ),
        migrations.RunPython(
            backfill_legacy_memberships,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.UniqueConstraint(
                fields=('active_identity_key',),
                name='accounts_membership_active_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.UniqueConstraint(
                fields=('pending_identity_key',),
                name='accounts_membership_pending_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        ('active_identity_key', models.F('student_profile_id')),
                        ('status', 'active'),
                    )
                    | models.Q(
                        models.Q(('status', 'active'), _negated=True),
                        ('active_identity_key__isnull', True),
                    )
                ),
                name='accounts_membership_active_key_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        ('pending_identity_key', models.F('student_profile_id')),
                        ('status', 'pending'),
                    )
                    | models.Q(
                        models.Q(('status', 'pending'), _negated=True),
                        ('pending_identity_key__isnull', True),
                    )
                ),
                name='accounts_membership_pending_key_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        ('record_source', 'legacy_backfill'),
                        ('requested_at__isnull', True),
                    )
                    | models.Q(
                        ('record_source', 'learner_request'),
                        ('requested_at__isnull', False),
                    )
                ),
                name='accounts_membership_request_time_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('decided_at__isnull', True),
                    models.Q(('status', 'active'), _negated=True),
                    ('started_at__isnull', False),
                    _connector='OR',
                ),
                name='accounts_membership_approval_time_ck',
            ),
        ),
    ]
