# Generated by Django 4.2.16 on 2026-08-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0004_assessment_explanation_versions'),
        ('accounts', '0014_enforce_membership_lifecycle_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_learners', to='riasec.pathway'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_subject_combination',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='journey_status',
            field=models.CharField(blank=True, choices=[('not_selected', 'Not yet selected a pathway'), ('selected', 'Already selected pathway and subjects'), ('currently_enrolled', 'Currently studying selected subjects'), ('reconsidering', 'Considering changing my selection'), ('unsure', 'Not sure')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='selection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='selection_source',
            field=models.CharField(blank=True, choices=[('smarta_shauri', 'Chosen in Smarta Shauri'), ('learner_reported', 'Reported by learner'), ('school_verified', 'Verified by school'), ('ministry_imported', 'Imported from ministry')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='selection_verified',
            field=models.BooleanField(default=False),
        ),
    ]
