# Generated by Django 4.2.16 on 2026-08-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_learner_journey_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentschoolmembership',
            name='accounts_membership_request_time_ck',
        ),
        migrations.RemoveConstraint(
            model_name='studentschoolmembership',
            name='accounts_membership_lifecycle_time_ck',
        ),
        migrations.AlterField(
            model_name='studentschoolmembership',
            name='record_source',
            field=models.CharField(choices=[('legacy_backfill', 'Legacy Backfill'), ('learner_request', 'Learner Request'), ('admin_import', 'School Admin Import')], default='learner_request', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('record_source', 'legacy_backfill'), ('requested_at__isnull', True)), models.Q(('record_source', 'admin_import'), ('requested_at__isnull', True)), models.Q(('record_source', 'learner_request'), ('requested_at__isnull', False)), _connector='OR'), name='accounts_membership_request_time_ck'),
        ),
        migrations.AddConstraint(
            model_name='studentschoolmembership',
            constraint=models.CheckConstraint(check=models.Q(('record_source', 'legacy_backfill'), models.Q(('decided_at__isnull', False), ('ended_at__isnull', True), ('record_source', 'admin_import'), ('started_at__isnull', False), ('status', 'active')), models.Q(('decided_at__isnull', True), ('ended_at__isnull', True), ('record_source', 'learner_request'), ('started_at__isnull', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('ended_at__isnull', True), ('record_source', 'learner_request'), ('started_at__isnull', False), ('status', 'active')), models.Q(('decided_at__isnull', False), ('ended_at__isnull', True), ('record_source', 'learner_request'), ('started_at__isnull', True), ('status', 'rejected')), models.Q(('decided_at__isnull', False), ('ended_at__isnull', False), ('record_source', 'learner_request'), ('started_at__isnull', False), ('status', 'ended')), _connector='OR'), name='accounts_membership_lifecycle_time_ck'),
        ),
    ]
