# Generated by Django 4.2.16 on 2026-06-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_studentprofile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('weight_r', models.FloatField()),
                ('weight_i', models.FloatField()),
                ('weight_a', models.FloatField()),
                ('weight_s', models.FloatField()),
                ('weight_e', models.FloatField()),
                ('weight_c', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RIASECAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riasec_assessments', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RIASECQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RIASECScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1)),
                ('raw_score', models.PositiveSmallIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='riasec.riasecassessment')),
            ],
            options={
                'unique_together': {('assessment', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='RIASECResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='riasec.riasecassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='riasec.riasecquestion')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('fit_score', models.FloatField()),
                ('fit_pct', models.PositiveSmallIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='riasec.riasecassessment')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='riasec.pathway')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('assessment', 'pathway'), ('assessment', 'rank')},
            },
        ),
    ]
