# Generated by Django 4.2.16 on 2026-06-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_studentprofile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('grade', models.IntegerField(choices=[(9, 'Grade 9'), (10, 'Grade 10')])),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['grade', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subjects', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.subject')),
            ],
            options={
                'unique_together': {('student_profile', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='CBCGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('year', models.IntegerField()),
                ('level', models.CharField(choices=[('EE1', 'Exceeding Expectation (lower)'), ('EE2', 'Exceeding Expectation (upper)'), ('ME1', 'Meeting Expectation (lower)'), ('ME2', 'Meeting Expectation (upper)'), ('AE1', 'Approaching Expectation (lower)'), ('AE2', 'Approaching Expectation (upper)'), ('BE1', 'Below Expectation (lower)'), ('BE2', 'Below Expectation (upper)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentsubject')),
            ],
            options={
                'ordering': ['year', 'term'],
                'unique_together': {('student_subject', 'term', 'year')},
            },
        ),
    ]
