# Generated by Django 4.2.16 on 2026-06-15 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(choices=[(9, 'Grade 9'), (10, 'Grade 10')], validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
