# Generated by Django 4.2.16 on 2026-08-01 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_enforce_membership_lifecycle_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0011_enforce_active_identity_and_protect_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuity_code', models.CharField(max_length=80)),
                ('active_identity', models.CharField(blank=True, editable=False, max_length=80, null=True)),
                ('current_level_code', models.CharField(editable=False, max_length=10)),
                ('current_level_rank', models.PositiveSmallIntegerField(editable=False)),
                ('current_framework_code', models.CharField(editable=False, max_length=80)),
                ('current_framework_version', models.CharField(editable=False, max_length=40)),
                ('target_level_code', models.CharField(editable=False, max_length=10)),
                ('target_level_rank', models.PositiveSmallIntegerField(editable=False)),
                ('target_framework_code', models.CharField(editable=False, max_length=80)),
                ('target_framework_version', models.CharField(editable=False, max_length=40)),
                ('target_term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('target_year', models.PositiveSmallIntegerField()),
                ('target_academic_grade', models.PositiveSmallIntegerField(choices=[(9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(12)])),
                ('action_plan', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('closed', 'Closed')], default='active', max_length=12)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_goals_created', to=settings.AUTH_USER_MODEL)),
                ('current_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_created_from_evidence', to='students.cbcgrade')),
                ('current_level_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_with_current_level', to='students.performanceleveldefinition')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_goals', to='accounts.studentprofile')),
                ('target_level_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_with_target_level', to='students.performanceleveldefinition')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicgoal',
            constraint=models.UniqueConstraint(fields=('learner', 'active_identity'), name='students_active_goal_identity_uniq'),
        ),
        migrations.AddConstraint(
            model_name='academicgoal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active_identity__isnull', False), ('status', 'active')), models.Q(('active_identity__isnull', True), ('status__in', ['achieved', 'closed'])), _connector='OR'), name='students_goal_status_identity_ck'),
        ),
    ]
