# Generated by Django 4.2.16 on 2026-08-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _isoformat(value):
    return value.isoformat() if value is not None else None


def backfill_factual_creation_snapshots(apps, schema_editor):
    AcademicGoal = apps.get_model('students', 'AcademicGoal')
    PerformanceLevelDefinition = apps.get_model(
        'students', 'PerformanceLevelDefinition'
    )
    goals = AcademicGoal.objects.select_related(
        'current_evidence__framework',
    )
    for goal in goals.iterator():
        evidence = goal.current_evidence
        level_ranks = dict(
            PerformanceLevelDefinition.objects.filter(
                framework_id=evidence.framework_id,
            ).values_list('code', 'rank')
        )
        snapshot = {
            'evidence_id': evidence.pk,
            'period': {
                'academic_grade': evidence.academic_grade,
                'year': evidence.year,
                'term': evidence.term,
            },
            'level': {
                'code': goal.current_level_code,
                'rank': goal.current_level_rank,
            },
            'framework': {
                'id': evidence.framework_id,
                'code': goal.current_framework_code,
                'version': goal.current_framework_version,
                'level_ranks': level_ranks,
            },
            'source': evidence.source,
            'verification': {
                'confidence': (
                    'school_verified'
                    if evidence.verified_at is not None
                    else 'learner_entered'
                ),
                'verified_by': evidence.verified_by_id,
                'verified_school': evidence.verified_school_id,
                'verified_at': _isoformat(evidence.verified_at),
            },
            'recorded_at': _isoformat(evidence.created_at),
            'snapshot_provenance': 'migration_0013_best_available',
        }
        updates = {'creation_evidence_snapshot': snapshot}
        if goal.status == 'achieved':
            updates['legacy_lifecycle_unverifiable'] = True
        elif goal.status == 'active' and any((
            goal.achieved_at,
            goal.closed_at,
        )):
            raise RuntimeError(
                'Cannot migrate an incoherent pre-existing active academic goal.'
            )
        elif goal.status == 'closed' and (
            goal.achieved_at is not None or goal.closed_at is None
        ):
            raise RuntimeError(
                'Cannot migrate an incoherent pre-existing closed academic goal.'
            )
        AcademicGoal.objects.filter(pk=goal.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0012_academic_goals'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicgoal',
            name='students_goal_status_identity_ck',
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='achievement_evidence_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='legacy_lifecycle_unverifiable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_goals_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='creation_evidence_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='academicgoal',
            name='current_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_created_from_evidence', to='students.cbcgrade'),
        ),
        migrations.RunPython(
            backfill_factual_creation_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='academicgoal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('achieved_at__isnull', True), ('achievement_evidence_snapshot__isnull', True), ('active_identity__isnull', False), ('closed_at__isnull', True), ('confirmed_by__isnull', True), ('legacy_lifecycle_unverifiable', False), ('status', 'active')), models.Q(('achieved_at__isnull', False), ('achievement_evidence_snapshot__isnull', False), ('active_identity__isnull', True), ('closed_at__isnull', True), ('confirmed_by__isnull', False), ('legacy_lifecycle_unverifiable', False), ('status', 'achieved')), models.Q(('achieved_at__isnull', True), ('achievement_evidence_snapshot__isnull', True), ('active_identity__isnull', True), ('closed_at__isnull', False), ('confirmed_by__isnull', True), ('legacy_lifecycle_unverifiable', False), ('status', 'closed')), models.Q(('achievement_evidence_snapshot__isnull', True), ('active_identity__isnull', True), ('closed_at__isnull', True), ('confirmed_by__isnull', True), ('legacy_lifecycle_unverifiable', True), ('status', 'achieved')), _connector='OR'), name='students_goal_lifecycle_coherence_ck'),
        ),
    ]
