# Generated by Django 4.2.16 on 2026-08-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


def _isoformat(value):
    return value.isoformat() if value is not None else None


def backfill_grade_level_definition_ids(apps, schema_editor):
    CBCGrade = apps.get_model('students', 'CBCGrade')
    PerformanceLevelDefinition = apps.get_model(
        'students', 'PerformanceLevelDefinition'
    )
    definitions = {
        (framework_id, code): definition_id
        for framework_id, code, definition_id in (
            PerformanceLevelDefinition.objects.values_list(
                'framework_id',
                'code',
                'pk',
            )
        )
    }
    for grade in CBCGrade.objects.only('pk', 'framework_id', 'level').iterator():
        definition_id = definitions.get((grade.framework_id, grade.level))
        if definition_id is not None:
            CBCGrade.objects.filter(pk=grade.pk).update(
                level_definition_id_snapshot=definition_id,
            )


def backfill_factual_creation_snapshots(apps, schema_editor):
    AcademicGoal = apps.get_model('students', 'AcademicGoal')
    PerformanceLevelDefinition = apps.get_model(
        'students', 'PerformanceLevelDefinition'
    )
    goals = AcademicGoal.objects.select_related(
        'current_evidence__framework',
        'target_level_definition',
    )
    for goal in goals.iterator():
        evidence = goal.current_evidence
        level_definitions = {
            str(definition_id): {'code': code, 'rank': rank}
            for definition_id, code, rank in (
                PerformanceLevelDefinition.objects.filter(
                    framework_id=evidence.framework_id,
                ).values_list('pk', 'code', 'rank')
            )
        }
        level_ranks = {
            definition['code']: definition['rank']
            for definition in level_definitions.values()
        }
        snapshot = {
            'evidence_id': evidence.pk,
            'period': {
                'academic_grade': evidence.academic_grade,
                'year': evidence.year,
                'term': evidence.term,
            },
            'level': {
                'code': goal.current_level_code,
                'rank': goal.current_level_rank,
                'definition_id': goal.current_level_definition_id,
            },
            'framework': {
                'id': evidence.framework_id,
                'code': goal.current_framework_code,
                'version': goal.current_framework_version,
                'level_ranks': level_ranks,
                'level_definitions': level_definitions,
            },
            'source': evidence.source,
            'verification': {
                'confidence': (
                    'school_verified'
                    if evidence.verified_at is not None
                    else 'learner_entered'
                ),
                'verified_by': evidence.verified_by_id,
                'verified_school': evidence.verified_school_id,
                'verified_at': _isoformat(evidence.verified_at),
            },
            'recorded_at': _isoformat(evidence.created_at),
            'snapshot_provenance': 'migration_0013_best_available',
        }
        normal_active = (
            goal.status == 'active'
            and goal.achieved_at is None
            and goal.closed_at is None
        )
        normal_closed = (
            goal.status == 'closed'
            and goal.achieved_at is None
            and goal.closed_at is not None
        )
        updates = {
            'creation_evidence_snapshot': snapshot,
            'target_framework_id_snapshot': goal.target_level_definition.framework_id,
            'legacy_lifecycle_unverifiable': not (normal_active or normal_closed),
        }
        AcademicGoal.objects.filter(pk=goal.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0012_academic_goals'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicgoal',
            name='students_goal_status_identity_ck',
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='achievement_evidence_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='legacy_lifecycle_unverifiable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='confirmed_by',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='academic_goals_confirmed',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='creation_evidence_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='academicgoal',
            name='target_framework_id_snapshot',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cbcgrade',
            name='level_definition_id_snapshot',
            field=models.PositiveBigIntegerField(
                editable=False,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='academicgoal',
            name='current_evidence',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=students.models.set_academic_goal_evidence_null,
                related_name='goals_created_from_evidence',
                to='students.cbcgrade',
            ),
        ),
        migrations.RunPython(
            backfill_grade_level_definition_ids,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_factual_creation_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='academicgoal',
            name='target_framework_id_snapshot',
            field=models.PositiveBigIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name='academicgoal',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        status='active',
                        legacy_lifecycle_unverifiable=False,
                        active_identity__isnull=False,
                        achieved_at__isnull=True,
                        closed_at__isnull=True,
                        confirmed_by__isnull=True,
                        achievement_evidence_snapshot__isnull=True,
                    )
                    | models.Q(
                        status='achieved',
                        legacy_lifecycle_unverifiable=False,
                        active_identity__isnull=True,
                        achieved_at__isnull=False,
                        closed_at__isnull=True,
                        confirmed_by__isnull=False,
                        confirmed_by=models.F('created_by'),
                        achievement_evidence_snapshot__isnull=False,
                    )
                    | models.Q(
                        status='closed',
                        legacy_lifecycle_unverifiable=False,
                        active_identity__isnull=True,
                        achieved_at__isnull=True,
                        closed_at__isnull=False,
                        confirmed_by__isnull=True,
                        achievement_evidence_snapshot__isnull=True,
                    )
                    | (
                        models.Q(
                            legacy_lifecycle_unverifiable=True,
                            confirmed_by__isnull=True,
                            achievement_evidence_snapshot__isnull=True,
                        )
                        & (
                            models.Q(
                                status='active',
                                active_identity__isnull=False,
                            )
                            | models.Q(
                                status__in=['achieved', 'closed'],
                                active_identity__isnull=True,
                            )
                        )
                    )
                ),
                name='students_goal_lifecycle_coherence_ck',
            ),
        ),
    ]
