# Generated by Django 4.2.25 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_harden_academic_goal_lifecycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentframework',
            options={
                'base_manager_name': 'objects',
                'ordering': ['scope', '-effective_date', 'code', 'version'],
            },
        ),
        migrations.AlterModelOptions(
            name='cbcgrade',
            options={
                'base_manager_name': 'objects',
                'ordering': ['year', 'term'],
            },
        ),
    ]
