# Generated by Django 4.2.25 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('students', '0014_guard_framework_activation_and_evidence_managers')]

    operations = [
        migrations.AlterModelOptions(
            name='performanceleveldefinition',
            options={'base_manager_name': 'objects', 'ordering': ['-rank', 'code']},
        ),
    ]
