# Generated by Django 4.2.16 on 2026-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assessment_submitted', 'Assessment Submitted'), ('counselor_note', 'Counselor Note'), ('parent_linked', 'Parent Linked'), ('counselor_assigned', 'Counselor Assigned'), ('child_assessment_complete', 'Child Assessment Complete')], max_length=30),
        ),
    ]
