# Generated by Django 4.2.16 on 2026-08-02 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_enforce_membership_lifecycle_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAdmissionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scope', models.CharField(max_length=120)),
                ('external_key', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=500)),
                ('education_framework', models.CharField(max_length=120)),
                ('admission_cycle', models.CharField(max_length=80)),
                ('effective_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('historical', 'Historical reference'), ('unavailable', 'Unavailable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_summary', models.TextField()),
            ],
            options={
                'ordering': ['-effective_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scope', models.CharField(max_length=120)),
                ('external_key', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=500)),
                ('education_framework', models.CharField(max_length=120)),
                ('admission_cycle', models.CharField(max_length=80)),
                ('effective_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('historical', 'Historical reference'), ('unavailable', 'Unavailable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=240)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('college', 'College'), ('tvet', 'TVET institution'), ('other', 'Other')], max_length=24)),
                ('county', models.CharField(blank=True, db_index=True, max_length=80)),
                ('website_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scope', models.CharField(max_length=120)),
                ('external_key', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=500)),
                ('education_framework', models.CharField(max_length=120)),
                ('admission_cycle', models.CharField(max_length=80)),
                ('effective_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('historical', 'Historical reference'), ('unavailable', 'Unavailable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('name', models.CharField(db_index=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='tertiary.institution')),
            ],
            options={
                'ordering': ['institution__name', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeSubjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scope', models.CharField(max_length=120)),
                ('external_key', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=500)),
                ('education_framework', models.CharField(max_length=120)),
                ('admission_cycle', models.CharField(max_length=80)),
                ('effective_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('historical', 'Historical reference'), ('unavailable', 'Unavailable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_code', models.CharField(db_index=True, max_length=80)),
                ('subject_name', models.CharField(max_length=160)),
                ('mapping_kind', models.CharField(choices=[('historical_requirement', 'Historical requirement'), ('exploratory_alignment', 'Exploratory alignment')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_references', to='tertiary.programme')),
            ],
            options={
                'ordering': ['subject_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LearnerEducationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('primary', 'Primary'), ('alternative', 'Alternative')], max_length=16)),
                ('priority', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education_goals_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_goals', to='tertiary.institution')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_goals', to='accounts.studentprofile')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learner_goals', to='tertiary.programme')),
            ],
            options={
                'ordering': ['kind', 'priority', 'created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['education_framework', 'admission_cycle'], name='tert_inst_frame_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['verification_status', 'name'], name='tert_inst_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('source_scope', 'external_key'), name='tertiary_inst_scope_external_uniq'),
        ),
        migrations.AddField(
            model_name='historicaladmissionreference',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_admission_references', to='tertiary.programme'),
        ),
        migrations.AddIndex(
            model_name='programmesubjectreference',
            index=models.Index(fields=['programme', 'mapping_kind'], name='tert_subj_prog_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='programmesubjectreference',
            constraint=models.UniqueConstraint(fields=('source_scope', 'external_key'), name='tertiary_subj_scope_external_uniq'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['institution', 'name'], name='tert_prog_inst_name_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['education_framework', 'admission_cycle'], name='tert_prog_frame_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['verification_status', 'name'], name='tert_prog_status_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('source_scope', 'external_key'), name='tertiary_prog_scope_external_uniq'),
        ),
        migrations.AddIndex(
            model_name='learnereducationgoal',
            index=models.Index(fields=['learner', 'kind'], name='tert_goal_learner_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnereducationgoal',
            constraint=models.UniqueConstraint(fields=('learner', 'kind', 'priority'), name='tertiary_goal_learner_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='learnereducationgoal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'primary'), ('priority', 1)), models.Q(('kind', 'alternative'), ('priority__in', [1, 2])), _connector='OR'), name='tertiary_goal_kind_priority_ck'),
        ),
        migrations.AddIndex(
            model_name='historicaladmissionreference',
            index=models.Index(fields=['programme', 'admission_cycle'], name='tert_hist_prog_cycle_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicaladmissionreference',
            constraint=models.UniqueConstraint(fields=('source_scope', 'external_key'), name='tertiary_hist_scope_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='historicaladmissionreference',
            constraint=models.CheckConstraint(check=models.Q(('education_framework', 'KCSE'), ('verification_status', 'historical')), name='tertiary_hist_kcse_reference_ck'),
        ),
    ]
