# Generated by Django 4.2.16 on 2026-08-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tertiary', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='programmesubjectreference',
            constraint=models.CheckConstraint(check=models.Q(('mapping_kind__in', ['historical_requirement', 'exploratory_alignment'])), name='tertiary_subj_mapping_kind_ck'),
        ),
    ]
