# Generated by Django 4.2.16 on 2026-06-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_registered', 'User registered'), ('email_verified', 'Email verified'), ('password_reset', 'Password reset'), ('account_deactivated', 'Account deactivated'), ('account_activated', 'Account activated'), ('invite_sent', 'Invite sent'), ('invite_accepted', 'Invite accepted'), ('school_created', 'School created'), ('school_edited', 'School edited'), ('school_deactivated', 'School deactivated'), ('school_activated', 'School activated'), ('counselor_added', 'Counselor added to school'), ('counselor_removed', 'Counselor removed from school'), ('counselor_assigned', 'Counselor assigned to student')], max_length=50)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('school', 'School'), ('assignment', 'Assignment')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='system_admin_action_0b1a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='system_admin_actor_1d3e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='system_admin_target_5a6b7c_idx'),
        ),
    ]
