# Generated by Django 4.2.16 on 2026-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0009_alter_auditlog_action_alter_auditlog_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('email_verified', 'Email verified'), ('password_reset', 'Password reset'), ('account_deactivated', 'Account deactivated'), ('account_activated', 'Account activated'), ('invite_sent', 'Invite sent'), ('invite_accepted', 'Invite accepted'), ('school_created', 'School created'), ('school_admin_provisioned', 'School admin provisioned'), ('school_edited', 'School edited'), ('school_deactivated', 'School deactivated'), ('school_activated', 'School activated'), ('counselor_added', 'Counselor added to school'), ('counselor_removed', 'Counselor removed from school'), ('counselor_assigned', 'Counselor assigned to student'), ('students_bulk_imported', 'Students bulk imported'), ('grade_verified', 'Grade verified'), ('grade_verification_removed', 'Grade verification removed'), ('school_marks_imported', 'School marks imported'), ('grade_definition_snapshot_rewritten', 'Grade definition snapshot rewritten'), ('school_membership_approved', 'School membership approved'), ('school_membership_rejected', 'School membership rejected'), ('framework_combination_status_changed', 'Framework combination status changed'), ('parent_link_approved', 'Parent link approved'), ('parent_link_revoked', 'Parent link revoked'), ('provisional_combination_changed', 'Provisional combination changed'), ('plan_review_status_changed', 'Plan review status changed'), ('report_downloaded', 'Report downloaded'), ('school_offerings_changed', 'School offerings changed')], max_length=50),
        ),
    ]
