# Generated by Django 4.2.16 on 2026-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselornote',
            name='visible_to_parent',
            field=models.BooleanField(default=False),
        ),
    ]
