"""PDF builders shared by school and counsellor cohort reports."""

import io

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from .components import data_table, empty_state, footer_disclaimer, report_header, section_title, stat_grid, text
from .theme import get_styles


def build_cohort_overview_report(data):
    buffer = io.BytesIO()
    styles = get_styles()
    document = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=15 * mm, bottomMargin=20 * mm,
    )
    elements = report_header(
        data['title'], data.get('subtitle', ''), data.get('generated_at'),
        data.get('logo_path'), styles,
    )
    elements.extend([
        section_title('Summary', styles),
        stat_grid(data.get('stats', []), styles),
    ])
    workload = data.get('counselor_workload') or []
    if workload:
        elements.extend([
            section_title('Counsellor Workload', styles),
            data_table(
                ['Counsellor', 'Active learners'],
                [[
                    Paragraph(text(row['counselor_name']), styles['BodyText2']),
                    row['student_count'],
                ] for row in workload],
                [125 * mm, 40 * mm],
            ),
        ])
    elements.extend([
        Spacer(1, 8 * mm),
        footer_disclaimer(
            data.get('disclaimer') or
            'Generated by Smarta Shauri for administrative guidance and planning.',
            styles,
        ),
    ])
    document.build(elements)
    return buffer.getvalue()


def build_cohort_roster_report(data):
    buffer = io.BytesIO()
    styles = get_styles()
    document = SimpleDocTemplate(
        buffer, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=12 * mm, bottomMargin=15 * mm,
    )
    elements = report_header(
        data['title'], data.get('subtitle', ''), data.get('generated_at'),
        data.get('logo_path'), styles,
    )
    rows = data.get('rows') or []
    if not rows:
        elements.append(empty_state('No learners match this filter.', styles))
    else:
        include_counselor = data.get('include_counselor', False)
        headers = ['Learner', 'Grade', 'RIASEC', 'Subjects', 'With evidence', 'Plan']
        widths = [55, 18, 27, 23, 29, 37]
        if include_counselor:
            headers.append('Counsellor')
            widths.append(48)
        table_rows = []
        for row in rows:
            values = [
                row['name'], row['grade'], row['riasec_status'],
                row['subjects_enrolled'], row['subjects_with_evidence'], row['plan_status'],
            ]
            if include_counselor:
                values.append(row['counselor'])
            table_rows.append([
                Paragraph(text(value), styles['SmallGrey']) for value in values
            ])
        elements.append(data_table(headers, table_rows, [width * mm for width in widths]))
    elements.extend([
        Spacer(1, 8 * mm),
        footer_disclaimer(
            'Generated by Smarta Shauri. This roster contains current administrative data.',
            styles,
        ),
    ])
    document.build(elements)
    return buffer.getvalue()
