"""System-administrator PDF report builders."""

import io

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from .components import data_table, empty_state, footer_disclaimer, report_header, section_title, stat_grid, text
from .theme import get_styles


def build_platform_overview_report(data):
    buffer = io.BytesIO()
    styles = get_styles()
    document = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=15 * mm, bottomMargin=20 * mm,
    )
    elements = report_header(
        'Platform Overview', 'Smarta Shauri rollout summary',
        data.get('generated_at'), data.get('logo_path'), styles,
    )
    elements.extend([
        section_title('Platform Summary', styles),
        stat_grid(data.get('stats', []), styles),
        section_title('County Footprint', styles),
    ])
    counties = data.get('counties') or []
    if counties:
        elements.append(data_table(
            ['County', 'Schools', 'Learners'],
            [[
                Paragraph(text(row['county']), styles['BodyText2']),
                row['schools'], row['learners'],
            ] for row in counties],
            [85 * mm, 40 * mm, 40 * mm],
        ))
    else:
        elements.append(empty_state('No county data is available.', styles))
    elements.extend([
        Spacer(1, 8 * mm),
        footer_disclaimer('Generated by Smarta Shauri for platform administration.', styles),
    ])
    document.build(elements)
    return buffer.getvalue()


def build_schools_directory_report(data):
    buffer = io.BytesIO()
    styles = get_styles()
    document = SimpleDocTemplate(
        buffer, pagesize=landscape(A4),
        leftMargin=15 * mm, rightMargin=15 * mm,
        topMargin=12 * mm, bottomMargin=15 * mm,
    )
    elements = report_header(
        'Schools Directory', 'Smarta Shauri registered schools',
        data.get('generated_at'), data.get('logo_path'), styles,
    )
    schools = data.get('schools') or []
    if schools:
        elements.append(data_table(
            ['School', 'County', 'Status', 'Learners', 'Counsellors'],
            [[
                Paragraph(text(row['name']), styles['BodyText2']),
                Paragraph(text(row['county']), styles['SmallGrey']),
                'Active' if row['is_active'] else 'Inactive',
                row['student_count'], row['counselor_count'],
            ] for row in schools],
            [100 * mm, 45 * mm, 35 * mm, 35 * mm, 35 * mm],
        ))
    else:
        elements.append(empty_state('No schools are registered.', styles))
    elements.extend([
        Spacer(1, 8 * mm),
        footer_disclaimer('Generated by Smarta Shauri for platform administration.', styles),
    ])
    document.build(elements)
    return buffer.getvalue()
