# Generated by Django 4.2.16 on 2026-07-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_correct_grade10_catalogue'),
        ('accounts', '0009_studentprofile_school_membership_status'),
        ('riasec', '0003_seed_pathways'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(max_length=500)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathwayTrack',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                (
                    'framework_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tracks',
                        to='guidance.frameworkversion',
                    ),
                ),
                (
                    'pathway',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='framework_tracks',
                        to='riasec.pathway',
                    ),
                ),
            ],
            options={
                'ordering': ['pathway__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                (
                    'framework_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='combinations',
                        to='guidance.frameworkversion',
                    ),
                ),
                (
                    'subject_one',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='combinations_as_subject_one',
                        to='students.subject',
                    ),
                ),
                (
                    'subject_three',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='combinations_as_subject_three',
                        to='students.subject',
                    ),
                ),
                (
                    'subject_two',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='combinations_as_subject_two',
                        to='students.subject',
                    ),
                ),
                (
                    'track',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='combinations',
                        to='guidance.pathwaytrack',
                    ),
                ),
            ],
            options={
                'ordering': ['track__pathway__name', 'track__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolOffering',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'combination',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='school_offerings',
                        to='guidance.subjectcombination',
                    ),
                ),
                (
                    'school',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='guidance_offerings',
                        to='accounts.school',
                    ),
                ),
            ],
            options={
                'ordering': ['school__name', 'combination__title'],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectcombination',
            constraint=models.UniqueConstraint(
                fields=('framework_version', 'code'),
                name='guidance_combo_fw_code_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='subjectcombination',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('subject_one', models.F('subject_two')),
                        _negated=True,
                    ),
                    models.Q(
                        ('subject_one', models.F('subject_three')),
                        _negated=True,
                    ),
                    models.Q(
                        ('subject_two', models.F('subject_three')),
                        _negated=True,
                    ),
                ),
                name='guidance_combo_subjects_distinct',
            ),
        ),
        migrations.AddConstraint(
            model_name='schooloffering',
            constraint=models.UniqueConstraint(
                fields=('school', 'combination'),
                name='guidance_school_combo_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='pathwaytrack',
            constraint=models.UniqueConstraint(
                fields=('framework_version', 'code'),
                name='guidance_track_fw_code_uniq',
            ),
        ),
    ]
