from .base import *
import os

DEBUG = False
ALLOWED_HOSTS = [os.environ['ALLOWED_HOST']]

_frontend_url = os.environ.get('FRONTEND_URL', '')
CORS_ALLOWED_ORIGINS = [_frontend_url] if _frontend_url else []

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
